- name: Install i3
  pacman: name={{item}}
  with_items:
    - xorg
    - xorg-init
    - i3
    - i3blocks
    - kitty
    - rofi
    - maim
    - feh
    - arandr
    - pavucontrol
    - nautilus
    - dunst
    - picom
    - copyq
    - bluez
    - bluez-utils
    - blueman
    - networkmanager
    - networkmanager-openvpn
    - network-manager-applet
    - playerctl
    - xclip
    - redshift
    - lxappearance
  tags:
    - i3
    - packages

- name: Install gruvbox gtk theme
  become: yes
  become_user: m47h4r
  ansible.builtin.command: trizen -S --noconfirm gruvbox-material-gtk-theme-git
  tags:
    - gtk theme
    - gruvbox
    - packages

- name: Install gruvbox icon theme
  become: yes
  become_user: m47h4r
  ansible.builtin.command: trizen -S --noconfirm gruvbox-material-icon-theme-git
  tags:
    - icon theme
    - gruvbox
    - packages

- name: Install gnome keyring
  pacman: name={{item}}
  with_items:
    - gnome-keyring
    - libsecret
    - libgnome-keyring
    - seahorse
  tags:
    - keyring
    - packages

- name: Append necessary configuration
  ansible.builtin.shell: 'echo -e "\nauth optional pam_gnome_keyring.so\nsession optional pam_gnome_keyring.so auto_start\n" >> /etc/pam.d/login'
  tags:
    - keyring
    - packages

- name: Create ~/Pictures directory
  become: yes
  become_user: m47h4r
  ansible.builtin.file:
    path: ~/Pictures
    state: directory
    mode: "0755"
  tags:
    - directory
    - system

- name: Enable & start bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - bluetooth-service
    - packages
