- name: Install i3
  pacman: name={{item}}
  with_items:
    - xorg
    - xorg-init
    - i3
    - i3blocks
    - kitty
    - rofi
    - maim
    - feh
    - arandr
    - pavucontrol
    - nautilus
    - dunst
    - picom
    - copyq
    - bluez
    - bluez-utils
    - blueman
    - networkmanager
    - networkmanager-openvpn
    - network-manager-applet
    - playerctl
    - xclip
    - redshift
    - lxappearance
  tags:
    - i3
    - packages

- name: Create ~/Pictures directory
  become: yes
  become_user: m47h4r
  ansible.builtin.file:
    path: ~/Pictures
    state: directory
    mode: "0755"
  tags:
    - directory
    - system

- name: Enable & start bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - bluetooth-service
    - packages
