- name: Checkout trizen repo if doesn't exist
  become: yes
  become_user: m47h4r
  ansible.builtin.git:
    repo: https://aur.archlinux.org/trizen-git.git
    dest: ~/.builds/trizen
    force: yes
    update: yes
  tags:
    - trizen

- name: Install trizen
  become: yes
  become_user: m47h4r
  ansible.builtin.command: makepkg -si --noconfirm
  args:
    chdir: ~/.builds/trizen
  tags:
    - trizen
